use std::fmt;
use std::marker::PhantomData;

use bytes::Bytes;
use serde::{Deserialize, Serialize};

use crate::client::Client;
use crate::error::Error;
use crate::template::FromExport;
use crate::BoxFuture;

/// Which server-side store the Downloader reads from. Determined by the
/// job that produced the file, never chosen by the caller on the normal
/// path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FileSystem {
    #[serde(rename = "integrationServer")]
    IntegrationServer,
    #[serde(rename = "reconciliation")]
    Reconciliation,
}

/// Handle to a file generated by an export or reconciliation job.
///
/// Carries the correct [`FileSystem`] (set by the producing operation) and
/// the template's output marker `F`, so downloads decode into the right
/// type. Serializable for persistence across processes; the serialized
/// form includes the file system, so a round trip preserves the pairing.
#[derive(Serialize, Deserialize)]
#[serde(bound(serialize = "", deserialize = ""))]
pub struct ExportedFile<F = Bytes> {
    name: String,
    file_system: FileSystem,
    #[serde(skip)]
    _out: PhantomData<fn() -> F>,
}

impl<F> ExportedFile<F> {
    pub(crate) fn from_response(name: String, file_system: FileSystem) -> Self {
        Self { name, file_system, _out: PhantomData }
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn file_system(&self) -> FileSystem {
        self.file_system
    }

    /// Drop the typed marker; downloads yield raw [`Bytes`].
    pub fn untyped(&self) -> ExportedFile<Bytes> {
        ExportedFile {
            name: self.name.clone(),
            file_system: self.file_system,
            _out: PhantomData,
        }
    }
}

impl ExportedFile<Bytes> {
    /// Escape hatch for filenames persisted out-of-band (e.g. a DB
    /// column). The caller asserts the file system; the library cannot
    /// verify it. Deliberately restricted to the untyped form.
    pub fn from_parts(name: impl Into<String>, file_system: FileSystem) -> Self {
        Self { name: name.into(), file_system, _out: PhantomData }
    }
}

impl<F> Clone for ExportedFile<F> {
    fn clone(&self) -> Self {
        Self {
            name: self.name.clone(),
            file_system: self.file_system,
            _out: PhantomData,
        }
    }
}

impl<F> fmt::Debug for ExportedFile<F> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ExportedFile")
            .field("name", &self.name)
            .field("file_system", &self.file_system)
            .finish()
    }
}

/// Downloader job (`type: "download"`). No options.
#[must_use = "actions do nothing until awaited"]
pub struct DownloadAction<F> {
    client: Client,
    name: String,
    file_system: FileSystem,
    _out: PhantomData<fn() -> F>,
}

impl<F> DownloadAction<F> {
    pub(crate) fn new(client: Client, file: &ExportedFile<F>) -> Self {
        Self {
            client,
            name: file.name.clone(),
            file_system: file.file_system,
            _out: PhantomData,
        }
    }
}

impl<F: FromExport> IntoFuture for DownloadAction<F> {
    type Output = Result<F::Output, Error>;
    type IntoFuture = BoxFuture<Self::Output>;

    fn into_future(self) -> Self::IntoFuture {
        Box::pin(async move {
            let _ = self;
            todo!()
        })
    }
}
